services:
  postgres:
    image: postgres:17
    container_name: nx-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: nx-backend
    command: sh -c "pnpm install && pnpm nx serve @org/api"
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - backend_node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      HUSKY: 0
      NX_DAEMON: 'false'
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: nx-frontend
    command: sh -c "pnpm install && pnpm nx serve @org/web --host=0.0.0.0"
    ports:
      - '4200:4200'
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      HUSKY: 0
      NX_DAEMON: 'false'
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
