name: Lint

on:
  push:
    branches:
      - dev/migrate-react-app

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prettier check
        run: npx nx format:check

      - name: Run ESLint from NX
        run: npx nx run-many --target=lint --all
